Repository puppetlabs/puppet, pull requests merged in 2018-04, with the labels that each got.

#6769 (PUP-8610) Speedup PuppetStack by adding top_of_stack and use that
  lib/puppet/error.rb
  lib/puppet/functions/break.rb
  lib/puppet/functions/empty.rb
  lib/puppet/functions/next.rb
  lib/puppet/functions/return.rb
  lib/puppet/functions/strftime.rb
  lib/puppet/parser/functions/create_resources.rb
  lib/puppet/parser/scope.rb
  lib/puppet/pops/evaluator/runtime3_support.rb
  lib/puppet/pops/puppet_stack.rb
  lib/puppet/pops/serialization/to_data_converter.rb
  spec/unit/parser/functions/create_resources_spec.rb
  spec/unit/pops/puppet_stack_spec.rb
Labels: Language

#6734 (PUP-8498) Make sure faulty resource ref is shown with location info
  lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
  spec/integration/parser/compiler_spec.rb
Labels: Language

#6778 (PUP-8240) make epp read with preserved line endings
  lib/puppet/pops/parser/epp_parser.rb
  lib/puppet/pops/parser/lexer2.rb
  spec/unit/functions/epp_spec.rb
Labels: Language, Windows

#6746 (PUP-8556) Add glob support to modulepath in environment.conf
  lib/puppet/settings/environment_conf.rb
  spec/unit/environments_spec.rb
Labels: Community
