Repository puppetlabs/puppet, pull requests merged in 2018-03, with the labels that each got.

#6688 (PUP-8496) move keys() and values() functions from stdlib to puppet
  lib/puppet/functions/keys.rb
  lib/puppet/functions/values.rb
  spec/unit/functions/keys_spec.rb
  spec/unit/functions/values_spec.rb
Labels: Language

#6673 (PUP-8482) Add Puppet Extended S-Expression Notation
  lib/puppet/face/epp.rb
  lib/puppet/face/parser.rb
  lib/puppet/pops/model/pn_transformer.rb
  lib/puppet/pops/parser/pn_parser.rb
  lib/puppet/pops/pn.rb
  spec/unit/face/epp_face_spec.rb
  spec/unit/face/parser_spec.rb
  spec/unit/pops/model/pn_transformer_spec.rb
  spec/unit/pops/parser/pn_parser_spec.rb
  spec/unit/pops/pn_spec.rb
Labels: Language

#6678 (PUP-8470) Use usermod to manage group membership when user forcelocal is true
  lib/puppet/provider/user/useradd.rb
  spec/unit/provider/user/useradd_spec.rb
Labels: Community

#6709 (PUP-8510) Enable custom new_function for ruby Object type implementations
  lib/puppet/pops/types/p_object_type.rb
  spec/unit/datatypes_spec.rb
Labels: Language

#6702 (PUP-8507) Add function `join` from stdlib to puppet
  lib/puppet/functions/join.rb
  spec/unit/functions/join_spec.rb
Labels: Language

#6434 (PUP-8232) Add back 'puppet facts upload' face and update
  api/docs/http_api_index.md
  api/docs/http_facts.md
  conf/auth.conf
  lib/puppet/application/facts.rb
  lib/puppet/face/facts.rb
  lib/puppet/indirector/facts/rest.rb
  lib/puppet/indirector/facts/yaml.rb
  lib/puppet/network/http/api/indirected_routes.rb
  spec/unit/face/facts_spec.rb
  spec/unit/indirector/facts/rest_spec.rb
  spec/unit/indirector/facts/yaml_spec.rb
  spec/unit/network/http/api/indirected_routes_spec.rb
Labels: #puppethack

#6706 (PUP-8495) Systemd support, Ubuntu 17.04 and 17.10
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: Community

#6733 (PUP-8545) Don't write directly to /dev/stdout
  lib/puppet/util/plist.rb
  spec/unit/util/plist_spec.rb
Labels: Community

#6699 (PUP-7307) Only tidy unmanaged files
  lib/puppet/type/tidy.rb
  spec/unit/type/tidy_spec.rb
Labels: Community

#6738 (PUP-8495) Systemd support, Ubuntu 18.04
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: Community

#6476 (PUP-4678) Allow yumrepo priority below the default
  lib/puppet/type/yumrepo.rb
  spec/unit/type/yumrepo_spec.rb
Labels: Community

#5717 (maint) Address incorrect argument passing within Puppet
  ext/upload_facts.rb
  lib/puppet/application.rb
  lib/puppet/application/face_base.rb
  lib/puppet/application/resource.rb
  lib/puppet/module_tool/dependency.rb
  lib/puppet/network/http/compression.rb
  lib/puppet/util/checksums.rb
  lib/puppet/util/instance_loader.rb
Labels: Agent
