Repository puppetlabs/puppet, pull requests merged in 2018-02, with the labels that each got.

#6317 (PUP-8098) adding 'acltype' as a valid property for a ZFS file system
  lib/puppet/provider/zfs/zfs.rb
  lib/puppet/type/zfs.rb
  spec/unit/provider/zfs/zfs_spec.rb
Labels: Community

#6625 (PUP-8231) Domain prefix Windows group members
  lib/puppet/util/windows/adsi.rb
  spec/integration/util/windows/adsi_spec.rb
  spec/unit/util/windows/adsi_spec.rb
Labels: Windows

#6644 (PUP-8267) Leverage beaker subcommands (again)
  acceptance/.beaker.yml
  acceptance/Gemfile
  acceptance/README-ec2.md
  acceptance/Rakefile
  acceptance/config/aio/options.rb
  acceptance/config/common/options.rb
  acceptance/config/gem/options.rb
  acceptance/config/git/options.rb
  acceptance/lib/puppet/acceptance/install_utils.rb
  acceptance/lib/puppet/acceptance/install_utils_spec.rb
  acceptance/setup/aio/pre-suite/010_Install.rb
  acceptance/setup/common/pre-suite/025_StopFirewall.rb
  acceptance/setup/git/pre-suite/010_TestSetup.rb
Labels: Blocked
