Repository puppetlabs/puppet, pull requests merged in 2018-09, with the labels that each got.

#7035 (PUP-8967) Request simple status to detect if server is functional
  acceptance/tests/server_list_setting.rb
  lib/puppet/configurer.rb
  lib/puppet/indirector/request.rb
  spec/unit/configurer_spec.rb
Labels: Blocked

#7019 (PUP-6964) Make all modules visible when making function calls
  lib/puppet/functions.rb
  lib/puppet/loaders.rb
  lib/puppet/parser/functions.rb
  lib/puppet/pops/evaluator/runtime3_converter.rb
  lib/puppet/pops/evaluator/runtime3_support.rb
  lib/puppet/pops/loader/loader.rb
  lib/puppet/pops/loader/loader_paths.rb
  lib/puppet/pops/loader/module_loaders.rb
  lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb
  lib/puppet/pops/loaders.rb
  spec/unit/pops/evaluator/evaluating_parser_spec.rb
  spec/unit/pops/loaders/loaders_spec.rb
Labels: Language

#7101 (PUP-9044) Fix puppet porage package provider for newer portage-utils versions
  lib/puppet/provider/package/portage.rb
Labels: Community
