Repository puppetlabs/puppet, pull requests merged in 2019-11, with the labels that each got.

#7794 (PUP-10102) fix service crash
  lib/puppet/provider/service/daemontools.rb
  lib/puppet/provider/service/runit.rb
  spec/unit/provider/service/daemontools_spec.rb
  spec/unit/provider/service/runit_spec.rb
Labels: Night's Watch

#7701 (PUP-10023) Expand the dpkg provider with virtual packages
  acceptance/tests/provider/package/dpkg_ensure_latest_virtual_packages.rb
  lib/puppet/provider/package/apt.rb
  lib/puppet/provider/package/dpkg.rb
  lib/puppet/type/package.rb
  spec/unit/provider/package/dpkg_spec.rb
  spec/unit/type/package_spec.rb
Labels: Night's Watch

#7803 (maint) fix pip tests on centos-8
  acceptance/tests/provider/package/pip.rb
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: Night's Watch

#7799 (PUP-10116) add dependency to beaker-gke
  acceptance/Gemfile
Labels: Night's Watch

#7768 (PUP-9562) User resource should respect forcelocal for the comment parameter
  lib/puppet/provider/user/useradd.rb
  spec/unit/provider/user/useradd_spec.rb
Labels: Night's Watch

#7808 (maint) fix runit and deamontools unit tests
  spec/unit/provider/service/daemontools_spec.rb
  spec/unit/provider/service/runit_spec.rb
Labels: Night's Watch

#7788 (PUP-9940) don't run puppet.bat on starting daemon
  ext/windows/service/daemon.rb
Labels: Night's Watch

#7781 (PUP-9940) don't run puppet.bat on starting deamon
  ext/windows/service/daemon.rb
Labels: Night's Watch

#7804 (PUP-9963) allow boolean for selboolean value
  lib/puppet/type/selboolean.rb
  spec/unit/type/selboolean_spec.rb
Labels: Night's Watch

#7816 (PUP-10104) Puppet device ssl oids
  lib/puppet/application/device.rb
  spec/unit/application/device_spec.rb
Labels: Community

#7494 (PUP-9650) ruby 2.6
  .travis.yml
  appveyor.yml
  lib/puppet/indirector/request.rb
  lib/puppet/pops/types/p_uri_type.rb
  lib/puppet/type/file/source.rb
  lib/puppet/util.rb
  spec/unit/pops/loaders/loaders_spec.rb
Labels: Coremunity

#7810 (PUP-10106) Don't require domain proxy exceptions to start with dot
  lib/puppet/defaults.rb
  lib/puppet/util/http_proxy.rb
  spec/unit/util/http_proxy_spec.rb
Labels: Coremunity

#7818 (maint) remove ja po file
  acceptance/tests/i18n/check_puppet_run_message.rb
  acceptance/tests/i18n/modules/puppet_apply.rb
  locales/ja/puppet.po
Labels: Coremunity

#7819 (maint) Drop ruby 24 and ja_JP from appveyor
  appveyor.yml
Labels: Coremunity

#7820 (maint) Drop ruby 24 & 25 with ja_JP from appveyor
  appveyor.yml
Labels: Coremunity

#7823 (maint) merge 5.5.x to 6.4.x
  acceptance/tests/i18n/check_puppet_run_message.rb
  acceptance/tests/i18n/modules/puppet_apply.rb
  lib/puppet/defaults.rb
  lib/puppet/util/http_proxy.rb
  man/man5/puppet.conf.5
  spec/unit/util/http_proxy_spec.rb
Labels: Night's Watch

#7739 (PUP-10033) HTTP Client
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/errors.rb
  lib/puppet/http/redirector.rb
  lib/puppet/http/response.rb
  lib/puppet/http/retry_after_handler.rb
  lib/puppet/network/http/pool.rb
  lib/puppet/network/http/site.rb
  spec/unit/configurer_spec.rb
  spec/unit/http/client_spec.rb
  spec/unit/network/http/site_spec.rb
Labels: Coremunity

#7833 (PUP-5934) Add optional fact refresh after applying catalog
  lib/puppet/configurer.rb
  lib/puppet/defaults.rb
  spec/integration/configurer_spec.rb
Labels: Coremunity

#7825 (PUP-10037) Add CA service
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/errors.rb
  lib/puppet/http/resolver.rb
  lib/puppet/http/resolver/settings.rb
  lib/puppet/http/resolver/srv.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/session.rb
  lib/puppet/network/resolver.rb
  spec/unit/http/client_spec.rb
  spec/unit/http/resolver_spec.rb
  spec/unit/http/service/ca_spec.rb
  spec/unit/http/service_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#7754 (maint) Do not use Ruby stacktrace for "Puppet" stack
  lib/puppet/pops/evaluator/runtime3_support.rb
  lib/puppet/pops/puppet_stack.rb
Labels: Server

#7826 (PUP-10040) Use http client for cert related requests
  lib/puppet.rb
  lib/puppet/application/ssl.rb
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/session.rb
  lib/puppet/network/http.rb
  lib/puppet/rest/errors.rb
  lib/puppet/rest/response.rb
  lib/puppet/rest/route.rb
  lib/puppet/rest/routes.rb
  lib/puppet/runtime.rb
  lib/puppet/ssl/state_machine.rb
  lib/puppet/util/http_proxy.rb
  spec/unit/http/client_spec.rb
  spec/unit/ssl/state_machine_spec.rb
Labels: Coremunity

#7843 (PUP-10140) Improve logging on windows service
  ext/windows/service/daemon.rb
Labels: Night's Watch

#7827 (PUP-10136) premature facts loading under facter -p
  lib/puppet/defaults.rb
  spec/unit/defaults_spec.rb
Labels: Night's Watch

#7727 (PUP-10017) coalesce resource dependency failures into class failures
  lib/puppet/defaults.rb
  lib/puppet/transaction.rb
  spec/unit/transaction_spec.rb
Labels: puppet-org

#7859 (DOCS) grammar fixes for find_file() function docs
  lib/puppet/functions/find_file.rb
Labels: puppet-org

#7857 (docs) Fixed puppet enterprise 404 link
  README.md
Labels: Community

#7589 (maint) add spec tests and correct debug output
  lib/puppet/provider/package_targetable.rb
  spec/unit/provider/package_targetable_spec.rb
Labels: puppet-org

#7860 (maint) Update GCE metadata endpoint
  spec/spec_helper.rb
Labels: Coremunity
