Repository puppetlabs/puppet, pull requests merged in 2019-07, with the labels that each got.

#7611 (PUP-9816) Fix `puppet parser validate` handling of STDIN
  lib/puppet/face/parser.rb
  spec/unit/face/parser_spec.rb
Labels: puppet-org

#7620 (PUP-9513) Deprecate Puppet::SSL::Host
  lib/puppet/indirector/certificate/file.rb
  lib/puppet/indirector/certificate/rest.rb
  lib/puppet/indirector/certificate_request/file.rb
  lib/puppet/indirector/certificate_request/memory.rb
  lib/puppet/indirector/certificate_request/rest.rb
  lib/puppet/indirector/key/file.rb
  lib/puppet/indirector/key/memory.rb
  lib/puppet/ssl/certificate.rb
  lib/puppet/ssl/host.rb
  lib/puppet/ssl/key.rb
Labels: merge when green

#7567 (PUP-9752) defaultfor for released Debian 10 and bullseye/sid
  lib/puppet/provider/service/systemd.rb
Labels: Community

#7523 (PUP-9699) Add recording of all looked up (hiera) keys
  lib/puppet/pops/lookup.rb
  lib/puppet/pops/lookup/key_recorder.rb
  lib/puppet/pops/lookup/lookup_adapter.rb
Labels: Blocked
