Repository puppetlabs/puppet, pull requests merged in 2019-09, with the labels that each got.

#7693 (maint) cleanup rspec requirements
  Gemfile
  spec/lib/puppet_spec/matchers.rb
  spec/spec_helper.rb
  spec/unit/face/help_spec.rb
  spec/unit/functions/contain_spec.rb
  spec/unit/node/environment_spec.rb
  spec/unit/provider/package/pkgin_spec.rb
  spec/unit/type/schedule_spec.rb
  spec/unit/util/inifile_spec.rb
Labels: puppet-org

#7685 (PUP-9933) Make indirector settings threadsafe
  lib/puppet/defaults.rb
  lib/puppet/indirector/indirection.rb
  lib/puppet/test/test_helper.rb
  spec/unit/indirector/indirection_spec.rb
Labels: Server

#7730 (PUP-9652) Delete audit delete tests
  acceptance/Rakefile
  acceptance/tests/allow_arbitrary_node_name_for_apply.rb
  acceptance/tests/apply/hashes/should_not_reassign.rb
  acceptance/tests/apply/puppet_apply_trace.rb
  acceptance/tests/cycle_detection.rb
  acceptance/tests/environment/3x_forbidden_environment_names_allowed.rb
  acceptance/tests/language/break.rb
  acceptance/tests/language/next.rb
  acceptance/tests/modules/install/basic_install.rb
  acceptance/tests/modules/search/multiple_search_terms.rb
  acceptance/tests/puppet_apply_should_show_a_notice.rb
  acceptance/tests/resource/service/ticket_14297_handle_upstart.rb
  acceptance/tests/ticket_4289_facter_should_recognize_OEL_operatingsystemrelease.rb
  acceptance/tests/ticket_4293_define_and_use_a_define_within_a_class.rb
  acceptance/tests/ticket_4404_should_allow_stage_main_on_left_side_of_relationship.rb
  acceptance/tests/ticket_4423_cannot_declare_two_parameterized_classes.rb
  spec/unit/pops/validator/validator_spec.rb
  spec/unit/util/log_spec.rb
Labels: puppet-org

#7738 (PUP-9933) Configure routes globally
  lib/puppet/indirector.rb
Labels: Server

#7587 (PUP-9787) Mask password on Forge URL if given
  lib/puppet/module_tool/applications/installer.rb
  lib/puppet/network/uri.rb
  spec/unit/network/uri_spec.rb
Labels: Community
