Repository puppetlabs/puppet, pull requests merged in 2019-12, with the labels that each got.

#7840 (PUP-10139) Add find_template function
  lib/puppet/functions/find_template.rb
  spec/unit/functions/find_template_spec.rb
Labels: puppet-org

#7822 (maint) Reset "tasks" setting after with_script_compiler
  lib/puppet/pal/pal_impl.rb
Labels: puppet-org

#7856 (PUP-10039) Add ServerList resolver
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/resolver.rb
  lib/puppet/http/resolver/server_list.rb
  lib/puppet/http/resolver/settings.rb
  lib/puppet/http/resolver/srv.rb
  lib/puppet/http/session.rb
  spec/unit/http/resolver_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#7850 (PUP-10144) Add method for loading system ssl context
  lib/puppet/ssl/ssl_provider.rb
  spec/integration/http/client_spec.rb
  spec/unit/ssl/ssl_provider_spec.rb
Labels: Coremunity

#7854 (PUP-10097) fix diff output for binary files
  acceptance/tests/resource/file/diff_output_content_attribute.rb
  lib/puppet/type/file/data_sync.rb
  spec/unit/type/file/content_spec.rb
Labels: Night's Watch

#7814 (PUP-10124) fix slot for portage package provider
  lib/puppet/provider/package/portage.rb
  spec/unit/provider/package/portage_spec.rb
Labels: Night's Watch

#7865 (maint) skip content diff test if UndefinedConversionError
  acceptance/tests/resource/file/ascii_diff_output_content_attribute.rb
  acceptance/tests/resource/file/bin_diff_output_content_attribute.rb
Labels: Night's Watch

#7812 (PUP-10057) User resource on Windows confuses domain and local accounts
  lib/puppet/util/windows/adsi.rb
  spec/unit/util/windows/adsi_spec.rb
Labels: Night's Watch

#7869 (maint) Merge up 5.5.x to 6.4.x
  acceptance/tests/resource/file/ascii_diff_output_content_attribute.rb
  acceptance/tests/resource/file/bin_diff_output_content_attribute.rb
  lib/puppet/provider/package/portage.rb
  lib/puppet/type/file/data_sync.rb
  lib/puppet/util/windows/adsi.rb
  man/man5/puppet.conf.5
  man/man8/puppet-agent.8
  man/man8/puppet-apply.8
  man/man8/puppet-catalog.8
  man/man8/puppet-config.8
  man/man8/puppet-describe.8
  man/man8/puppet-device.8
  man/man8/puppet-doc.8
  man/man8/puppet-epp.8
  man/man8/puppet-facts.8
  man/man8/puppet-filebucket.8
  man/man8/puppet-generate.8
  man/man8/puppet-help.8
  man/man8/puppet-key.8
  man/man8/puppet-man.8
  man/man8/puppet-module.8
  man/man8/puppet-node.8
  man/man8/puppet-parser.8
  man/man8/puppet-plugin.8
  man/man8/puppet-report.8
  man/man8/puppet-resource.8
  man/man8/puppet-script.8
  man/man8/puppet-status.8
  man/man8/puppet.8
  spec/unit/provider/package/portage_spec.rb
  spec/unit/type/file/content_spec.rb
  spec/unit/util/windows/adsi_spec.rb
Labels: Night's Watch

#7868 (PUP-10162) Add support for Cumulus v4.0.0
  lib/puppet/provider/service/systemd.rb
Labels: Community, Night's Watch

#7872 (PUP-9391) HP-UX usermod/userdel syntax order fix
  lib/puppet/provider/user/hpux.rb
  spec/unit/provider/user/hpux_spec.rb
Labels: Night's Watch

#7875 (maint) Create man directories before manpage generation
  tasks/manpages.rake
Labels: Night's Watch

#7732 (PUP-10024) Add locking around environments
  lib/puppet/concurrent.rb
  lib/puppet/concurrent/lock.rb
  lib/puppet/concurrent/synchronized.rb
  lib/puppet/concurrent/thread_local_singleton.rb
  lib/puppet/environments.rb
  lib/puppet/node/environment.rb
  lib/puppet/pops/parser/evaluating_parser.rb
  lib/puppet/pops/time/timespan.rb
  lib/puppet/pops/types/type_parser.rb
  spec/unit/concurrent/lock_spec.rb
Labels: Server

#7876 (PUP-7113) Document AIX local resource functionality
  lib/puppet/type/group.rb
  lib/puppet/type/user.rb
Labels: Night's Watch

#7867 (PUP-10157) Observe ServerList Resolver
  lib/puppet/http/client.rb
  lib/puppet/http/resolver/server_list.rb
  spec/unit/http/resolver_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#7863 (PUP-10170) Do not use Ruby stacktrace for "Puppet" stack
  lib/puppet/pops/evaluator/runtime3_support.rb
  lib/puppet/pops/puppet_stack.rb
Labels: Server

#7877 (maint) Add a rake task to run tests with docker
  acceptance/Rakefile
  acceptance/config/git/options.rb
Labels: Coremunity

#7878 (maint) Print TLS connection info at debug level
  lib/puppet/network/http/base_pool.rb
  spec/integration/http/client_spec.rb
Labels: Coremunity

#7864 (PUP-10041) Convert puppet module tool to http client
  lib/puppet/forge.rb
  lib/puppet/forge/errors.rb
  lib/puppet/forge/repository.rb
  lib/puppet/http/client.rb
  spec/fixtures/unit/forge/bacula.json
  spec/integration/http/client_spec.rb
  spec/integration/module_tool/forge_spec.rb
  spec/lib/puppet_spec/https.rb
  spec/lib/puppet_spec/validators.rb
  spec/unit/forge/errors_spec.rb
  spec/unit/forge/forge_spec.rb
  spec/unit/forge/module_release_spec.rb
  spec/unit/forge/repository_spec.rb
  spec/unit/forge_spec.rb
  spec/unit/http/client_spec.rb
  spec/unit/network/http/connection_spec.rb
Labels: Coremunity

#7884 (maint) update nightly gems path
  ext/build_defaults.yaml
Labels: Night's Watch

#7885 (maint) update nightly gems path
  ext/build_defaults.yaml
Labels: Night's Watch

#7766 (PUP-10091) Add FacterNg dependency
  Gemfile
  lib/puppet/defaults.rb
  spec/unit/defaults_spec.rb
Labels: Night's Watch

#7874 (PUP-10160) Defer catalog transformation until after environment convergence
  lib/puppet/configurer.rb
  lib/puppet/network/http/pool.rb
  spec/unit/configurer_spec.rb
Labels: Coremunity

#7895 (maint) Merge 5.5.x to 6.4.x
  lib/puppet/configurer.rb
  lib/puppet/network/http/pool.rb
  spec/unit/configurer_spec.rb
Labels: Coremunity

#7893 (PUP-10165) Allow hostprivkey and hostcert to override certname
  lib/puppet/x509/cert_provider.rb
  spec/unit/x509/cert_provider_spec.rb
Labels: Coremunity
