Repository puppetlabs/puppet, pull requests merged in 2019-10, with the labels that each got.

#7762 (maint) Merge 5.5.x to 6.4.x
  lib/puppet/module_tool/tar/mini.rb
  spec/unit/network/http/api/indirected_routes_spec.rb
  spec/unit/type/file/source_spec.rb
  spec/unit/type/schedule_spec.rb
Labels: Coremunity

#7758 (PUP-10013) Update minitar in Gemfile in 6.4 and newer
  Gemfile
Labels: Coremunity

#7757 (PUP-9295) Redact sensitive notify messages
  lib/puppet/type/notify.rb
  spec/integration/type/notify_spec.rb
Labels: Coremunity

#7751 (PUP-8986) Parse multiple lines of pip --version output
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: Coremunity

#7767 (PUP-10053) Update to more recent webmock and vcr
  Gemfile
  spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_handling_requests/_request_get/should_yield_to_the_block.yml
  spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_handling_requests/_request_head/should_yield_to_the_block.yml
  spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_handling_requests/_request_post/should_yield_to_the_block.yml
  spec/spec_helper.rb
  spec/unit/application/ssl_spec.rb
  spec/unit/network/http/connection_spec.rb
  spec/unit/ssl/host_spec.rb
  spec/unit/ssl/state_machine_spec.rb
  spec/unit/util/http_proxy_spec.rb
Labels: Coremunity

#7752 (PUP-9647) Quote pip path when calling execpipe
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: Coremunity

#7755 (maint) Improve Kernel.caller() usage
  .rubocop.yml
  lib/puppet/functions.rb
  lib/puppet/util/log.rb
  lib/puppet/util/logging.rb
Labels: Server

#7763 (PUP-10026) document skip_tags option for the puppet agent
  lib/puppet/application/agent.rb
Labels: Community

#7775 (PUP-5915) Stop Exec defaulting its cwd parameter
  lib/puppet/provider/exec.rb
  spec/unit/util/execution_spec.rb
Labels: Coremunity

#7748 (PUP-9978) Support for DNF modules
  acceptance/tests/provider/package/dnfmodule_ensure_versionable.rb
  lib/puppet/provider/package/dnfmodule.rb
  lib/puppet/type/package.rb
  spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list-installed.txt
  spec/unit/provider/package/dnfmodule_spec.rb
Labels: Night's Watch

#7780 (PUP-10021) Allow password change for disabled users
  acceptance/lib/puppet/acceptance/windows_utils.rb
  acceptance/tests/windows/enable_password_changes_special_users.rb
  acceptance/tests/windows/prevent_password_changes.rb
  lib/puppet/provider/user/windows_adsi.rb
Labels: Night's Watch

#7402 (PUP-9509) Puppet 3 API functions should be loaded from cache
  lib/puppet/pops/loader/module_loaders.rb
  spec/unit/pops/loaders/loaders_spec.rb
Labels: puppet-org

#7791 (PUP-10112) Use Net::HTTP.new instead of Net::HTTP::Proxy
  lib/puppet/util/http_proxy.rb
  spec/unit/forge/forge_spec.rb
  spec/unit/forge/repository_spec.rb
  spec/unit/util/http_proxy_spec.rb
Labels: Coremunity

#7795 (PUP-10014) Remove deep_merge as a vendored gem
  .gemspec
  ext/project_data.yaml
  lib/puppet/vendor/deep_merge/CHANGELOG
  lib/puppet/vendor/deep_merge/Gemfile
  lib/puppet/vendor/deep_merge/LICENSE
  lib/puppet/vendor/deep_merge/PUPPET_README.md
  lib/puppet/vendor/deep_merge/README.md
  lib/puppet/vendor/deep_merge/Rakefile
  lib/puppet/vendor/deep_merge/deep_merge.gemspec
  lib/puppet/vendor/deep_merge/lib/deep_merge.rb
  lib/puppet/vendor/deep_merge/lib/deep_merge/core.rb
  lib/puppet/vendor/deep_merge/lib/deep_merge/deep_merge_hash.rb
  lib/puppet/vendor/deep_merge/lib/deep_merge/rails_compat.rb
  lib/puppet/vendor/deep_merge/test/test_deep_merge.rb
  lib/puppet/vendor/load_deep_merge.rb
  lib/puppet/vendor/require_vendored.rb
Labels: Coremunity

#7784 (PUP-10100) Redact sensitive data from arguments and failed commands
  lib/puppet/provider/exec.rb
  lib/puppet/type/exec.rb
  spec/unit/provider/exec_spec.rb
  spec/unit/type/exec_spec.rb
Labels: Coremunity

#7633 PUP-8949 use install_options with 'latest' methods
  acceptance/tests/provider/package/pip.rb
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: Night's Watch, puppet-org

#7801 (maint) Exclude tests on JRuby
  spec/unit/provider/exec_spec.rb
Labels: Night's Watch
