Repository puppetlabs/puppet, pull requests merged in 2019-04, with the labels that each got.

#7406 (maint) Relax fast_gettext gem constraint
  .gemspec
  ext/project_data.yaml
Labels: Community

#7444 (maint) Amazon linux reports majrelease as '2018'
  lib/puppet/provider/package/yum.rb
  spec/unit/provider/package/yum_spec.rb
Labels: Community

#7462 (PUP-9584) optimize pluginsync for devices
  lib/puppet/application/device.rb
  spec/unit/application/device_spec.rb
Labels: Blocked

#7474 (docs) Clarify `period => never`
  lib/puppet/type/schedule.rb
Labels: puppet-org

#7480 (docs) exec resources are non-isomorphic (duplicate namevars allowed)
  lib/puppet/type/exec.rb
Labels: Community

#7320 (PUP-9395) specify version-specific documentation params with install
  lib/puppet/provider/package/gem.rb
  spec/unit/provider/package/gem_spec.rb
  spec/unit/provider/package/puppet_gem_spec.rb
Labels: puppet-org

#7477 (PUP-9055) Expose function similar to `puppet master --compile`
  lib/puppet/face/catalog.rb
Labels: Community

#7322 (PUP-9389) Add staging_location parameter to File
  lib/puppet/type/file.rb
  lib/puppet/util.rb
  spec/unit/type/file_spec.rb
  spec/unit/util_spec.rb
Labels: Community

#6909 (PUP-8984) Add --format=json option to `puppet parser validate`
  lib/puppet/error.rb
  lib/puppet/face/parser.rb
  spec/unit/face/parser_spec.rb
Labels: puppet-org
