Repository puppetlabs/puppet, pull requests merged in 2020-04, with the labels that each got.

#8061 (PUP-10376) preseve file ownership on replace
  acceptance/tests/windows/PUP-9719_windows_system_first_pa_run.rb
  lib/puppet/file_system/file_impl.rb
  spec/unit/file_system_spec.rb
Labels: Night's Watch

#8056 (PUP-10295) Add range intersection support to gem package provider
  acceptance/tests/provider/package/gem.rb
  lib/puppet/provider/package/gem.rb
  lib/puppet/util/package/version/gem.rb
  lib/puppet/util/package/version/range/min_max.rb
Labels: Night's Watch

#8067 (PUP-10322) Update facterng feature flag not to use Kernel.require
  lib/puppet/defaults.rb
  spec/unit/defaults_spec.rb
Labels: Night's Watch

#8053 (PUP-10380) Add support for install_options to pkgng
  lib/puppet/provider/package/pkgng.rb
  spec/unit/provider/package/pkgng_spec.rb
Labels: Community, Night's Watch

#8055 (PUP-10382) Ignore packages of which the latest version is not in the index
  lib/puppet/provider/package/pkgng.rb
  spec/fixtures/unit/provider/package/pkgng/pkg.version
  spec/unit/provider/package/pkgng_spec.rb
Labels: Community, Night's Watch

#8064 (PUP-10152) Prevent Pacman package provider doing partial upgrades
  lib/puppet/provider/package/pacman.rb
  spec/unit/provider/package/pacman_spec.rb
Labels: Community, Night's Watch

#8060 (PUP-10393) Fix ruby 2.7 warning
  lib/puppet/file_system/file_impl.rb
Labels: Community

#8030 (PUP-10298) Yum version range support
  acceptance/tests/provider/package/yum_semantic_versioning.rb
  lib/puppet/provider/package/rpm.rb
  lib/puppet/provider/package/yum.rb
  lib/puppet/util/package/version/rpm.rb
  lib/puppet/util/rpm_compare.rb
  spec/unit/provider/package/yum_spec.rb
  spec/unit/util/package/version/rpm_spec.rb
Labels: Night's Watch

#8076 (PUP-10376) specify the full path for the schtask
  acceptance/tests/windows/PUP-9719_windows_system_first_pa_run.rb
Labels: Night's Watch

#8071 (PUP-10405) Fix `undefined method` error when querying environments
  lib/puppet/environments.rb
  spec/unit/environments_spec.rb
Labels: Server

#8077 (PUP-10385) Change filebucket terminus to use http client
  lib/puppet/application/filebucket.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/indirector/file_bucket_file/rest.rb
  spec/integration/application/filebucket_spec.rb
  spec/lib/puppet_spec/puppetserver.rb
  spec/unit/application/filebucket_spec.rb
Labels: Coremunity

#8073 (PUP-10401) Pip package provider outputs warning on puppet run
  lib/puppet/provider/package/pip3.rb
Labels: Night's Watch

#8066 (maint) Verify POST requests detect EOF
  spec/integration/http/client_spec.rb
Labels: Coremunity

#8079 (maint) JRuby SSLSocket#cipher returns a string unlike MRI
  lib/puppet/network/http/base_pool.rb
Labels: Coremunity

#8082 (docs)(DOCUMENT-1035) Edits from user feedback
  lib/puppet/functions/reduce.rb
Labels: puppet-org

#8068 (PUP-10379) Load bolt project into environment module list
  lib/puppet/node/environment.rb
  spec/integration/node/environment_spec.rb
  spec/unit/node/environment_spec.rb
Labels: puppet-org

#8075 (PUP-10390) Ruby file gets loaded twice
  lib/puppet/provider/package/gem.rb
  lib/puppet/provider/package/puppet_gem.rb
Labels: Night's Watch

#8052 (PUP-10248) Windows pidlock can raise access denied
  lib/puppet/util/pidlock.rb
  lib/puppet/util/windows/process.rb
  lib/puppet/util/windows/security.rb
  spec/unit/util/pidlock_spec.rb
Labels: Night's Watch

#8063 (PUP-10397) Remove facts and vars from ScriptCompiler scope
  lib/puppet/pal/pal_impl.rb
  spec/unit/puppet_pal_2pec.rb
Labels: puppet-org

#8085 (PUP-10385) Migrate the filebucket rest terminus to the new http client code
  acceptance/tests/ticket_4622_filebucket_diff_test.rb
  lib/puppet/application/filebucket.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/indirector/file_bucket_file/rest.rb
  spec/integration/application/filebucket_spec.rb
  spec/unit/application/filebucket_spec.rb
  spec/unit/http/service/compiler_spec.rb
  spec/unit/indirector/file_bucket_file/rest_spec.rb
Labels: Coremunity

#8083 (maint) Use callback to report on resolver exceptions
  lib/puppet/http/resolver.rb
  lib/puppet/http/resolver/server_list.rb
  lib/puppet/http/resolver/settings.rb
  lib/puppet/http/resolver/srv.rb
  lib/puppet/http/session.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#8086 (maint) Don't clear "stale" pid when running parallel:spec
  lib/puppet/util/pidlock.rb
  spec/unit/util/pidlock_spec.rb
Labels: Coremunity

#8074 (PUP-10366) defense to `exit` calls
  lib/puppet/agent.rb
  spec/unit/agent_spec.rb
Labels: Night's Watch

#8087 (PUP-10371) Add metric for total agent runtime
  lib/puppet/application/agent.rb
  lib/puppet/configurer.rb
  lib/puppet/transaction/report.rb
  lib/puppet/util/at_fork.rb
  lib/puppet/util/platform.rb
  spec/unit/application/agent_spec.rb
  spec/unit/configurer_spec.rb
  spec/unit/transaction/report_spec.rb
  spec/unit/util/at_fork_spec.rb
Labels: Night's Watch

#8098 (maint) do not explicitly call `exit` in `run_in_fork`
  lib/puppet/agent.rb
Labels: Night's Watch

#8089 (PUP-10378) 'puppet resource service' omitting services on Ubuntu
  lib/puppet/provider/service/systemd.rb
  spec/fixtures/unit/provider/service/systemd/list_unit_files_services
  spec/unit/provider/service/systemd_spec.rb
Labels: Night's Watch

#8096 (PUP-10418) Unify service return values
  lib/puppet/application/ssl.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/file_server.rb
  lib/puppet/indirector/catalog/rest.rb
  lib/puppet/indirector/facts/rest.rb
  lib/puppet/indirector/file_bucket_file/rest.rb
  lib/puppet/indirector/file_metadata/rest.rb
  lib/puppet/indirector/node/rest.rb
  lib/puppet/indirector/status/rest.rb
  lib/puppet/ssl/state_machine.rb
  spec/unit/http/service/ca_spec.rb
  spec/unit/http/service/compiler_spec.rb
  spec/unit/http/service/file_server_spec.rb
  spec/unit/http/service/report_spec.rb
Labels: Coremunity

#8078 (PUP-10228) Release ssl lockfile while sleeping
  lib/puppet/ssl/state_machine.rb
  spec/unit/ssl/state_machine_spec.rb
Labels: Coremunity

#8093 (PUP-10414) Replace deprecated calls to `--configprint`
  ext/windows/service/daemon.rb
Labels: Night's Watch

#8101 (PUP-8051) waitforlock and maxwaitforlock setting
  lib/puppet/agent.rb
  lib/puppet/defaults.rb
  spec/integration/application/agent_spec.rb
Labels: Coremunity, Night's Watch

#8102 (PUP-10416) Yum package provider fixes.
  lib/puppet/provider/package/rpm.rb
  lib/puppet/provider/package/yum.rb
  lib/puppet/util/package/version/rpm.rb
  lib/puppet/util/rpm_compare.rb
  spec/unit/provider/package/rpm_spec.rb
  spec/unit/provider/package/yum_spec.rb
  spec/unit/util/package/version/rpm_spec.rb
  spec/unit/util/rpm_compare_spec.rb
Labels: Night's Watch

#8109 (PUP-10432) Fix yum provider check_updates.
  lib/puppet/provider/package/yum.rb
  spec/fixtures/unit/provider/package/yum/yum-check-update-subscription-manager.txt
  spec/unit/provider/package/yum_spec.rb
Labels: Night's Watch

#8091 (PUP-10375) Latest package version for pip provider fixed
  lib/puppet/provider/package/pip.rb
  lib/puppet/util/package/version/pip.rb
  spec/unit/provider/package/pip_spec.rb
  spec/unit/util/package/version/pip_spec.rb
Labels: Night's Watch

#8107 (PUP-8937) Check AIX package state after install
  lib/puppet/provider/package/aix.rb
  spec/unit/provider/package/aix_spec.rb
Labels: Night's Watch

#8112 (PUP-10437) systemd provider listing static services fix
  lib/puppet/provider/service/systemd.rb
  spec/fixtures/unit/provider/service/systemd/list_unit_files_services
  spec/unit/provider/service/systemd_spec.rb
Labels: Night's Watch

#8105 (PUP-10429) Allow puppetserver to register http implementation
  lib/puppet.rb
  lib/puppet/network/http_pool.rb
  lib/puppet/runtime.rb
  spec/unit/network/http_pool_spec.rb
  spec/unit/puppet_spec.rb
Labels: Coremunity

#8095 (PUP-10299) Add SemVerRange support to zypper
  acceptance/fixtures/sles-repo/noarch/helloworld-1.0-2.noarch.rpm
  acceptance/fixtures/sles-repo/noarch/helloworld-1.19-2.noarch.rpm
  acceptance/fixtures/sles-repo/noarch/helloworld-2.0-2.noarch.rpm
  acceptance/fixtures/sles-repo/repodata/filelists.xml.gz
  acceptance/fixtures/sles-repo/repodata/other.xml.gz
  acceptance/fixtures/sles-repo/repodata/primary.xml.gz
  acceptance/fixtures/sles-repo/repodata/repomd.xml
  acceptance/tests/provider/package/apt_install_package_with_range.rb
  acceptance/tests/provider/package/zypper_install_package_with_range.rb
  lib/puppet/provider/package/zypper.rb
  spec/fixtures/unit/provider/package/zypper/zypper-search-uninstalled.out
  spec/unit/provider/package/zypper_spec.rb
Labels: Night's Watch

#8110 (PUP-7663) -1 instead if '' when expiry = :absent
  acceptance/tests/resource/user/should_create_with_expiry_absent.rb
  lib/puppet/provider/user/useradd.rb
  spec/unit/provider/user/useradd_spec.rb
Labels: Night's Watch

#8108 (PUP-7163) systemd provider 'indirect' service fix
  lib/puppet/provider/service/systemd.rb
  lib/puppet/type/service.rb
  spec/unit/provider/service/systemd_spec.rb
  spec/unit/type/service_spec.rb
Labels: Night's Watch

#8124 (maint) Merge up 5c8f9a to master fix
  spec/unit/provider/service/systemd_spec.rb
Labels: Night's Watch

#8114 (PUP-10469) Fix portage package provider confine
  lib/puppet/provider/package/portage.rb
  spec/unit/provider/package/portage_spec.rb
Labels: Community, Night's Watch
