Repository puppetlabs/puppet, pull requests merged in 2020-03, with the labels that each got.

#8005 (PUP-10317) Provide better error when hiera-eyaml decryption fails
  lib/puppet/functions/eyaml_lookup_key.rb
  spec/unit/functions/lookup_spec.rb
Labels: Community

#8008 (PUP-10260) Use http client for rest requests
  lib/puppet/configurer.rb
  lib/puppet/http/service/report.rb
  lib/puppet/indirector/catalog/rest.rb
  lib/puppet/indirector/facts/rest.rb
  lib/puppet/indirector/file_content/rest.rb
  lib/puppet/indirector/file_metadata/rest.rb
  lib/puppet/indirector/node/rest.rb
  lib/puppet/indirector/report/rest.rb
  lib/puppet/indirector/rest.rb
  lib/puppet/indirector/status/rest.rb
  lib/puppet/type/file/source.rb
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_fetch_if_not_on_the_local_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_not_update_if_content_on_disk_is_up-to-date.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_update_if_content_differs_on_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_mtime_is_older_on_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_no_header_specified.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_not_on_the_local_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_not_update_if_mtime_is_newer_on_disk.yml
  spec/unit/configurer_spec.rb
  spec/unit/http/service/report_spec.rb
  spec/unit/indirector/catalog/rest_spec.rb
  spec/unit/indirector/facts/rest_spec.rb
  spec/unit/indirector/file_content/rest_spec.rb
  spec/unit/indirector/file_metadata/rest_spec.rb
  spec/unit/indirector/node/rest_spec.rb
  spec/unit/indirector/report/rest_spec.rb
  spec/unit/indirector/status/rest_spec.rb
Labels: Coremunity

#8003 (PUP-10314) Skip ssl debug for non-ssl connections
  lib/puppet/http/client.rb
  lib/puppet/network/http/base_pool.rb
  lib/puppet/network/http/pool.rb
  spec/unit/network/http/pool_spec.rb
Labels: Coremunity

#8002 (PUP-9932) Add locking around loaders
  lib/puppet/loaders.rb
Labels: Server

#7997 (maint) update some readmes
  COMMITTERS.md
  CONTRIBUTING.md
  README.md
Labels: puppet-org

#8015 (PUP-10347) Reconnect when using a cached connection
  lib/puppet/http/client.rb
  spec/integration/http/client_spec.rb
  spec/integration/network/http_pool_spec.rb
Labels: Coremunity

#8013 (PUP-10320) update group membership user check
  lib/puppet/provider/group/groupadd.rb
  spec/unit/provider/group/groupadd_spec.rb
Labels: Night's Watch

#8012 (PUP-10315) Use http client to process the server list
  lib/puppet/configurer.rb
  lib/puppet/http/resolver/server_list.rb
  spec/unit/http/resolver_spec.rb
Labels: Coremunity

#8021 (maint) upgrade rake due to CVE-2020-8130
  acceptance/Gemfile
Labels: Night's Watch

#8020 (maint) curl should follow redirect when downloading
  .gemspec
  acceptance/tests/aix/aix_package_provider.rb
Labels: Night's Watch

#8027 (maint) Restrict where aix nim test runs
  acceptance/tests/aix/nim_package_provider.rb
Labels: Coremunity

#8025 (PUP-10353) Replace keyword arguments to generic options hash
  lib/puppet/forge/repository.rb
  lib/puppet/http/client.rb
  lib/puppet/http/resolver/server_list.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/report.rb
  spec/integration/http/client_spec.rb
  spec/unit/http/client_spec.rb
  spec/unit/http/service_spec.rb
Labels: Coremunity

#8028 (PUP-10363) Process server list once per session
  lib/puppet/http/client.rb
  lib/puppet/http/resolver/server_list.rb
  spec/unit/http/resolver_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#8023 (PUP-10325) Update mode in yaml report
  lib/puppet/indirector/report/yaml.rb
  spec/integration/indirector/report/yaml.rb
Labels: Night's Watch

#8022 (PUP-10357) Basic implementation of Version::Range
  lib/puppet/util/package/version/range.rb
  lib/puppet/util/package/version/range/gt.rb
  lib/puppet/util/package/version/range/gt_eq.rb
  lib/puppet/util/package/version/range/lt.rb
  lib/puppet/util/package/version/range/lt_eq.rb
  lib/puppet/util/package/version/range/min_max.rb
  lib/puppet/util/package/version/range/simple.rb
  spec/unit/util/package/version/range_spec.rb
Labels: Night's Watch

#8035 (PUP-10363) Cache the server list url not the service
  lib/puppet/http/resolver/server_list.rb
  spec/unit/http/resolver_spec.rb
Labels: Coremunity

#8032 (PUP-10355) Don't emit a deprecation warning when using http_instance
  lib/puppet.rb
  lib/puppet/ssl/host.rb
  spec/integration/network/http_pool_spec.rb
  spec/unit/ssl/host_spec.rb
Labels: Coremunity

#8026 (PUP 10297) add version range support for apt
  acceptance/fixtures/debian-repo/Packages.gz
  acceptance/fixtures/debian-repo/Release
  acceptance/fixtures/debian-repo/helloworld_1.0-1.deb
  acceptance/fixtures/debian-repo/helloworld_1.19-1.deb
  acceptance/fixtures/debian-repo/helloworld_2.0-1.deb
  acceptance/tests/provider/package/apt_install_packet_with_range.rb
  lib/puppet/provider/package/apt.rb
  lib/puppet/util/package/version/debian.rb
  spec/unit/provider/package/apt_spec.rb
  spec/unit/util/package/version/debian_spec.rb
Labels: Night's Watch

#8034 (PUP-10362) Better rspec integration coverage for agent functionality
  acceptance/tests/reports/failover_master.rb
  spec/integration/application/agent_spec.rb
  spec/lib/puppet_spec/puppetserver.rb
Labels: Coremunity

#8036 (PUP-10365) Fix https file source regression
  lib/puppet/type/file/source.rb
  spec/fixtures/ssl/unknown-127.0.0.1-key.pem
  spec/fixtures/ssl/unknown-127.0.0.1.pem
  spec/fixtures/ssl/unknown-ca-key.pem
  spec/fixtures/ssl/unknown-ca.pem
  spec/integration/application/agent_spec.rb
  spec/lib/puppet/test_ca.rb
  spec/lib/puppet_spec/https.rb
  tasks/generate_cert_fixtures.rake
Labels: Coremunity

#8031 (PUP-10364) Add pp_owner ppRegCertExt OID
  lib/puppet/ssl/oids.rb
  spec/unit/ssl/oids_spec.rb
Labels: puppet-org

#8041 (maint) Run package resource acceptance in CI - 5.5.x branch
  acceptance/fixtures/el-repo/RPMS/kernel-devel-puppet-3.10.0-1062.1.1.noarch.rpm
  acceptance/fixtures/el-repo/RPMS/kernel-devel-puppet-3.10.0-1062.4.3.noarch.rpm
  acceptance/fixtures/el-repo/repodata/23c1cdf4888dad216dae92d5cf2d6c72442890bdee0ae76215de6cfb50453793-filelists.sqlite.bz2
  acceptance/fixtures/el-repo/repodata/3279cda77715780b8f79e09a8e150203a588ceb3964b4c0d040effb621f04f94-filelists.xml.gz
  acceptance/fixtures/el-repo/repodata/82c5fef41035ac8cdd102e83fe64663ae98b85ebab8c5abe002345a65a9da154-primary.xml.gz
  acceptance/fixtures/el-repo/repodata/cb2b76bfeb5f6013864cd82bc2fcfb4d7a96b5a49dbddfe88ca842caca9979b6-other.xml.gz
  acceptance/fixtures/el-repo/repodata/f47e7d9d0bd4c74de1430e2563b6cf4b10cd36a947a32d93aef8d9adfd7d339d-primary.sqlite.bz2
  acceptance/fixtures/el-repo/repodata/f9033be663b799c484326a0c278424bf93b7637cf2f0158203e74b164019b6ab-other.sqlite.bz2
  acceptance/fixtures/el-repo/repodata/repomd.xml
  acceptance/tests/provider/package/dnfmodule_ensure_versionable.rb
  acceptance/tests/provider/package/dnfmodule_manages_flavors.rb
  acceptance/tests/provider/package/dpkg_ensure_held_package_should_preserve_version.rb
  acceptance/tests/provider/package/dpkg_hold_true_package_is_latest.rb
  acceptance/tests/provider/package/dpkg_hold_true_should_preserve_version.rb
  acceptance/tests/provider/package/rpm_ensure_install_multiversion_package.rb
Labels: Night's Watch

#8042 (maint) Run package resource acceptance in CI - master branch
  acceptance/tests/provider/package/dpkg_ensure_latest_virtual_packages.rb
Labels: Night's Watch

#8037 (PUP-10367) Source files using full_path
  lib/puppet/type/file/source.rb
  spec/integration/application/apply_spec.rb
Labels: Coremunity

#8046 (PUP-10374) Download from the locales mount
  lib/puppet/configurer/plugin_handler.rb
  lib/puppet/face/plugin.rb
  spec/integration/application/plugin_spec.rb
  spec/integration/faces/plugin_spec.rb
Labels: Coremunity

#7998 (MODULES-7319) Call "semodule --list" only once.
  lib/puppet/provider/selmodule/semodule.rb
  spec/unit/provider/selmodule_spec.rb
Labels: Community, Night's Watch

#8039 (PUP-10348) Update resubmit_facts description
  lib/puppet/defaults.rb
Labels: Coremunity

#8058 (maint) unify log messages with other providers
  lib/puppet/provider/package/apt.rb
  spec/unit/provider/package/apt_spec.rb
Labels: Night's Watch

#8038 (PUP-10354) Add yardocs for Puppet::HTTP::Client
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/redirector.rb
  lib/puppet/http/resolver.rb
  lib/puppet/http/resolver/server_list.rb
  lib/puppet/http/resolver/settings.rb
  lib/puppet/http/resolver/srv.rb
  lib/puppet/http/response.rb
  lib/puppet/http/retry_after_handler.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/file_server.rb
  lib/puppet/http/service/report.rb
  lib/puppet/http/session.rb
  lib/puppet/ssl.rb
Labels: Coremunity

#8009 (PUP-10319) Invalidate rubygems cache after uninstalling puppet_gem package
  lib/puppet/provider/package/puppet_gem.rb
  spec/unit/provider/package/puppet_gem_spec.rb
Labels: Community

#8051 (PUP-10324) Adapt HTTP API to puppetserver's external implementation
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/external_client.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/report.rb
  lib/puppet/network/http_pool.rb
  spec/unit/http/client_spec.rb
  spec/unit/http/external_client_spec.rb
Labels: Coremunity

#7994 (PUP-10296) Add version range support to pip package provider
  acceptance/tests/provider/package/pip.rb
  lib/puppet/provider/package/pip.rb
  lib/puppet/util/package/version/pip.rb
  spec/unit/util/package/version/pip_spec.rb
Labels: Night's Watch

#8054 (PUP-10316) Update "http" report processor to use the http client
  lib/puppet/reports/http.rb
  spec/integration/application/agent_spec.rb
  spec/integration/application/apply_spec.rb
  spec/integration/application/plugin_spec.rb
  spec/integration/http/client_spec.rb
  spec/integration/module_tool/forge_spec.rb
  spec/lib/puppet_spec/https.rb
  spec/shared_contexts/https.rb
  spec/unit/reports/http_spec.rb
Labels: Coremunity

#8057 (PUP-7737) Allow http report processor to trust the system CA store
  lib/puppet/defaults.rb
  lib/puppet/reports/http.rb
  spec/integration/application/apply_spec.rb
Labels: Coremunity

#8059 (maint) default to systemd also on Ubuntu 20.04
  lib/puppet/provider/service/systemd.rb
Labels: Do Not Merge, Night's Watch

#8016 (PUP-10322) Set puppet logger in facter-ng.
  lib/puppet/defaults.rb
  spec/unit/defaults_spec.rb
Labels: Night's Watch

#8047 (PUP-10235) Support enabling DNF modules
  acceptance/tests/provider/package/dnfmodule_enable_only.rb
  lib/puppet/provider/package/dnfmodule.rb
  lib/puppet/type/package.rb
  spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list-enabled.txt
  spec/unit/provider/package/dnfmodule_spec.rb
Labels: Night's Watch

#8044 (PUP-10303) unresolvable domain accounts handling
  lib/puppet/provider/group/windows_adsi.rb
  lib/puppet/util/windows/adsi.rb
  lib/puppet/util/windows/sid.rb
  spec/integration/util/windows/adsi_spec.rb
  spec/unit/provider/group/windows_adsi_spec.rb
  spec/unit/provider/user/windows_adsi_spec.rb
  spec/unit/util/windows/adsi_spec.rb
  spec/unit/util/windows/sid_spec.rb
Labels: Night's Watch
