Repository puppetlabs/puppet, pull requests merged in 2020-05, with the labels that each got.

#8116 (PUP-10444) Deprecate http file content terminus
  lib/puppet/indirector/file_content/http.rb
Labels: Coremunity

#8129 (maint) Avoid transient error due to empty password
  spec/integration/util/windows/adsi_spec.rb
Labels: Coremunity

#8128 (PUP-10471) Use symbols for implementation names
  lib/puppet.rb
  lib/puppet/application/device.rb
  lib/puppet/application/ssl.rb
  lib/puppet/configurer.rb
  lib/puppet/face/facts.rb
  lib/puppet/face/plugin.rb
  lib/puppet/forge/repository.rb
  lib/puppet/reports/http.rb
  lib/puppet/runtime.rb
  lib/puppet/ssl/state_machine.rb
  lib/puppet/test/test_helper.rb
  lib/puppet/type/file/source.rb
  spec/unit/network/http_pool_spec.rb
  spec/unit/puppet_spec.rb
  spec/unit/reports/http_spec.rb
  spec/unit/ssl/state_machine_spec.rb
Labels: Coremunity

#8125 (PUP-10477) remove non-local return from agent.rb
  lib/puppet/agent.rb
  spec/unit/agent_spec.rb
Labels: Night's Watch

#8117 (PUP-10445) Deprecate base rest methods
  lib/puppet/indirector/rest.rb
  spec/unit/indirector/rest_spec.rb
Labels: Coremunity

#8131 (PUP-10482) Use http client for http file metadata
  lib/puppet/indirector/file_metadata/http.rb
  spec/integration/application/agent_spec.rb
  spec/integration/http/client_spec.rb
  spec/lib/puppet_spec/https.rb
  spec/unit/indirector/file_metadata/http_spec.rb
  spec/unit/indirector/file_metadata/rest_spec.rb
Labels: Coremunity

#8136 (PUP-10480) Deprecate 'puppet module search'
  lib/puppet/face/module/search.rb
  spec/unit/face/module/search_spec.rb
Labels: Coremunity

#8132 (PUP-10164) Parse Content-MD5 leniently
  lib/puppet/file_serving/http_metadata.rb
  spec/unit/indirector/file_metadata/http_spec.rb
Labels: Coremunity

#8134 (PUP-10433) Add --no-gpg-checks as global option
  lib/puppet/provider/package/zypper.rb
  spec/unit/provider/package/zypper_spec.rb
Labels: Night's Watch

#8126 (PUP-10479) systemd wrongly reports enabled state
  acceptance/tests/resource/service/systemd_resource_shows_correct_output.rb
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: Night's Watch

#8113 (PUP-10351) Puppet Agent fails to self-restart
  lib/puppet/agent.rb
  lib/puppet/daemon.rb
  spec/unit/daemon_spec.rb
Labels: Night's Watch

#8133 (PUP-10485) quote pip path when it has spaces
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: Night's Watch, puppet-org

#8147 (PUP-10351) Puppet Agent fails to self-restart
  lib/puppet/agent.rb
Labels: Night's Watch

#8137 (PUP-10419) disable for dnf module
  acceptance/tests/provider/package/dnfmodule_ensure_versionable.rb
  lib/puppet/provider/package/dnfmodule.rb
  lib/puppet/type/package.rb
  spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list.txt
  spec/unit/provider/package/dnfmodule_spec.rb
Labels: Night's Watch

#8135 (maint) Server as daemon cleanup
  lib/puppet/application/agent.rb
  lib/puppet/daemon.rb
  spec/unit/application/agent_spec.rb
  spec/unit/daemon_spec.rb
Labels: Night's Watch

#8148 (PUP-8051) waitforlock and maxwaitforlock setting
  lib/puppet/agent.rb
  lib/puppet/defaults.rb
  spec/integration/application/agent_spec.rb
  spec/unit/agent_spec.rb
Labels: Night's Watch

#8119 (PUP-10292) Evaluate trusted-external lazily
  lib/puppet/context/trusted_information.rb
  spec/unit/context/trusted_information_spec.rb
Labels: Coremunity, puppet-org

#8097 (PUP-10420) Allow state machine to retry ssl lock
  lib/puppet/ssl/state_machine.rb
  spec/unit/ssl/state_machine_spec.rb
Labels: Coremunity

#8156 (PUP-10289) Route HttpPool requests to the HTTP client
  lib/puppet/http/client.rb
  lib/puppet/indirector/rest.rb
  lib/puppet/network/http/connection_adapter.rb
  lib/puppet/network/http_pool.rb
  lib/puppet/runtime.rb
  lib/puppet/ssl/verifier_adapter.rb
  spec/unit/network/http/connection_spec.rb
  spec/unit/network/http_pool_spec.rb
Labels: Coremunity

#8100 (PUP-10407) Don't chown log file destination
  lib/puppet/util/log/destinations.rb
  spec/unit/util/log/destinations_spec.rb
Labels: Coremunity

#8160 (docs) fixed small errors
  docs/catalogs.md
  docs/http.md
Labels: Community

#8157 (PUP-10506) Fix `purge_ssh_keys` requiring homedir
  lib/puppet/type/user.rb
  spec/unit/type/user_spec.rb
Labels: Night's Watch

#8161 (docs) fix filter function documentation code block
  lib/puppet/functions/filter.rb
  lib/puppet/parser/functions/filter.rb
Labels: Community

#8138 (PUP-10496) Fix parsing version range for regular version
  lib/puppet/provider/package/apt.rb
  lib/puppet/provider/package/pip.rb
  lib/puppet/provider/package/yum.rb
  lib/puppet/provider/package/zypper.rb
  lib/puppet/util/package/version/range.rb
  lib/puppet/util/package/version/range/eq.rb
  spec/unit/provider/package/yum_spec.rb
  spec/unit/util/package/version/range_spec.rb
Labels: Community, Night's Watch

#8143 (docs) add note to clarify enable param
  lib/puppet/type/service.rb
Labels: puppet-org

#8165 (PUP-10524) Address spec failures when running with facter 4
  .gemspec
  spec/unit/indirector/catalog/compiler_spec.rb
  spec/unit/provider/service/init_spec.rb
  spec/unit/provider/service/openbsd_spec.rb
  spec/unit/provider/service/openwrt_spec.rb
  spec/unit/provider/service/redhat_spec.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: Coremunity

#8171 (maint) Fix maxwaitforlock integration test
  spec/integration/application/agent_spec.rb
Labels: Night's Watch
