Repository puppetlabs/puppet, pull requests merged in 2020-06, with the labels that each got.

#8158 (PUP-8897) Fix `managehome` property for `useradd`
  lib/puppet/provider/user/useradd.rb
  spec/unit/provider/user/openbsd_spec.rb
  spec/unit/provider/user/useradd_spec.rb
Labels: Night's Watch

#8179 (PUP-10537) Resolve Ruby 2.7 Warnings
  .travis.yml
  Gemfile
  acceptance/Gemfile
  lib/puppet/confine.rb
  lib/puppet/file_serving/metadata.rb
  lib/puppet/file_system/file_impl.rb
  lib/puppet/file_system/uniquefile.rb
  lib/puppet/indirector.rb
  lib/puppet/parser/ast/leaf.rb
  lib/puppet/parser/ast/pops_bridge.rb
  lib/puppet/parser/compiler.rb
  lib/puppet/parser/environment_compiler.rb
  lib/puppet/provider/package/aptitude.rb
  lib/puppet/provider/package/yum.rb
  lib/puppet/resource.rb
  lib/puppet/ssl/ssl_context.rb
  lib/puppet/type.rb
  lib/puppet/util.rb
  lib/puppet/util/fileparsing.rb
  lib/puppet/util/provider_features.rb
  lib/puppet/util/reference.rb
  spec/unit/interface_spec.rb
  spec/unit/parser/ast/block_expression_spec.rb
  spec/unit/parser/scope_spec.rb
  spec/unit/pops/loaders/loaders_spec.rb
  spec/unit/pops/types/type_calculator_spec.rb
  spec/unit/resource_spec.rb
  spec/unit/ssl/ssl_provider_spec.rb
  spec/unit/transaction/report_spec.rb
  spec/unit/x509/cert_provider_spec.rb
Labels: Coremunity

#8173 (PUP-10528) Extend trusted_external_command to support a directory
  acceptance/tests/ssl/trusted_external_facts.rb
  lib/puppet/defaults.rb
  lib/puppet/trusted_external.rb
  spec/unit/context/trusted_information_spec.rb
Labels: puppet-org

#8183 (PUP-10536) read until wide null or string length
  lib/puppet/util/windows/api_types.rb
  lib/puppet/util/windows/registry.rb
  spec/integration/util/windows/registry_spec.rb
  spec/unit/util/windows/api_types_spec.rb
Labels: Night's Watch

#8184 (PUP-10511) fix resource array with sensitive parameters
  lib/puppet/parser/resource.rb
  lib/puppet/parser/resource/param.rb
  spec/integration/parser/compiler_spec.rb
Labels: Night's Watch

#8174 (PUP-10510) Set correct title when collecting resources
  lib/puppet/type.rb
  spec/unit/type_spec.rb
Labels: Night's Watch

#8185 (PUP-10527) Test puppet service runs puppet
  acceptance/tests/resource/service/puppet_service_runs_puppet.rb
Labels: puppet-org

#8202 (maint) Fix segfault due to invalid SID in tests
  lib/puppet/util/windows/principal.rb
Labels: Coremunity

#8199 (PUP-10543) Fallback to partial GET if HEAD request to puppetserver fails
  lib/puppet/indirector/file_metadata/http.rb
  spec/unit/indirector/file_metadata/http_spec.rb
Labels: Coremunity

#8193 (PUP-10542) Generate AST for apply blocks with 0 statements
  lib/puppet/pops/evaluator/evaluator_impl.rb
  spec/unit/pops/evaluator/evaluating_parser_spec.rb
Labels: puppet-org
