Repository puppetlabs/puppet, pull requests merged in 2020-01, with the labels that each got.

#7892 (PUP-10148) Include X-Puppet-Profiling Header
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  spec/unit/http/client_spec.rb
  spec/unit/http/service/ca_spec.rb
Labels: Coremunity

#7898 (PUP-10213) Do not create unused exceptions in evaluation
  lib/puppet/pops/evaluator/runtime3_support.rb
  spec/unit/pops/evaluator/evaluating_parser_spec.rb
Labels: Server

#7897 (PUP-10038) Add Report HTTP Service
  lib/puppet/http.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/report.rb
  spec/unit/http/service/report_spec.rb
Labels: Coremunity

#7915 (PUP-10219) Windows confuses domain/local accounts
  lib/puppet/util/windows/adsi.rb
  spec/unit/util/windows/adsi_spec.rb
Labels: Night's Watch

#7913 (PUP-10163) Add thread safety for singletons using Visitor
  lib/puppet/pops/model/pn_transformer.rb
  lib/puppet/pops/serialization/json_path.rb
  lib/puppet/pops/types/string_converter.rb
  lib/puppet/pops/types/type_calculator.rb
  lib/puppet/pops/types/type_formatter.rb
Labels: Server

#7917 (PUP-10222) Make Lookup Invocation parent thread local
  lib/puppet/pops/lookup/invocation.rb
Labels: Server

#7910 (maint) Update tests to actually not require a master host when running
  acceptance/tests/catalog_with_binary_data.rb
  acceptance/tests/language/binary_data_type.rb
  acceptance/tests/language/objects_in_catalog.rb
  acceptance/tests/lookup/lookup.rb
  acceptance/tests/lookup/lookup_rich_values.rb
  acceptance/tests/modules/list/with_environment.rb
  acceptance/tests/reports/agent_sends_json_report_for_cached_catalog.rb
  acceptance/tests/reports/corrective_change_via_puppet.rb
  acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
  acceptance/tests/server_returns_pson_when_preferred_serialization_set.rb
  acceptance/tests/ssl/autosign_command.rb
  acceptance/tests/ssl/certificate_extensions.rb
  acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb
  acceptance/tests/utf8/utf8-in-catalog.rb
Labels: Coremunity

#7922 (PUP-10234) Add ppAuthCertExt to custom_extensions
  lib/puppet/defaults.rb
  lib/puppet/ssl/certificate.rb
  spec/unit/ssl/certificate_spec.rb
Labels: Coremunity

#7879 (PUP-10177) Fixes scan_options parser with yum package provider
  lib/puppet/provider/package/yum.rb
  spec/unit/provider/package/yum_spec.rb
Labels: Community, Night's Watch

#7916 (PUP-10146) Add File HTTP Service
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/file_server.rb
  spec/unit/http/client_spec.rb
  spec/unit/http/service/compiler_spec.rb
  spec/unit/http/service/file_server_spec.rb
  spec/unit/http/service/report_spec.rb
Labels: Coremunity

#7911 (maint) remove references to master where we don't need them
  acceptance/tests/resource/exec/should_run_command_in_cwd.rb
Labels: Coremunity

#7924 (PUP-10146) Stream file content response body
  lib/puppet/http/service/file_server.rb
  spec/unit/http/service/file_server_spec.rb
Labels: Coremunity

#7909 (PUP-10223) Allow node definitions in apply blocks
  lib/puppet/pops/loader/puppet_plan_instantiator.rb
  lib/puppet/pops/validation/checker4_0.rb
  lib/puppet/pops/validation/tasks_checker.rb
  spec/unit/pops/validator/validator_spec.rb
Labels: puppet-org

#7676 (PUP-9966) acceptance tests for package gem provider
  acceptance/tests/provider/package/gem.rb
Labels: Night's Watch, puppet-org

#7866 (PUP-10117) Read passwd and group files once per resource
  lib/puppet/provider/group/groupadd.rb
  lib/puppet/provider/user/useradd.rb
  spec/unit/provider/group/groupadd_spec.rb
  spec/unit/provider/user/useradd_spec.rb
Labels: Night's Watch

#7932 (PUP-10232) Use HTTP client to resubmit facts
  lib/puppet/configurer.rb
  spec/integration/configurer_spec.rb
Labels: Coremunity

#7928 (PUP-10113) Speed up method calls and calls to []
  benchmarks/type_inference/site.pp.erb
  lib/puppet/pops/evaluator/access_operator.rb
  lib/puppet/pops/evaluator/evaluator_impl.rb
  lib/puppet/pops/types/type_calculator.rb
Labels: Coremunity

#7931 (PUP-8900) Use HTTP client to upload facts
  lib/puppet/face/facts.rb
  spec/unit/face/facts_spec.rb
Labels: Coremunity

#7935 (PUP-10241) Force UTF-8 encoding on XML plist data
  acceptance/tests/resource/file/ticket_8740_should_not_enumerate_root_directory.rb
  acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb
  acceptance/tests/resource/user/should_modify_home.rb
  acceptance/tests/resource/user/should_modify_uid.rb
  lib/puppet/util/plist.rb
  spec/unit/util/plist_spec.rb
Labels: Night's Watch

#7940 (PUP-2820) Print meaningful disable_warnings error message
  lib/puppet/defaults.rb
Labels: Coremunity

#7941 (PUP-3721) Include provider parameter in puppet resource output
  lib/puppet/application/resource.rb
  spec/unit/application/resource_spec.rb
Labels: Coremunity

#7939 (maint) Delete sync requires
  lib/puppet/configurer.rb
  lib/puppet/util/storage.rb
Labels: Coremunity

#7906 (PUP-10171) Support changing package flavors
  acceptance/tests/provider/package/dnfmodule_manages_flavors.rb
  lib/puppet/provider/package/dnfmodule.rb
  lib/puppet/provider/package/openbsd.rb
  lib/puppet/type/package.rb
  spec/unit/provider/package/dnfmodule_spec.rb
  spec/unit/provider/package/openbsd_spec.rb
  spec/unit/type/package_spec.rb
Labels: Night's Watch

#7807 (PUP-9719) Fix Administrators Group Windows Permissions
  acceptance/tests/windows/PUP-9719_windows_system_first_pa_run.rb
  lib/puppet/file_system/windows.rb
  lib/puppet/indirector/file_bucket_file/file.rb
  lib/puppet/indirector/json.rb
  lib/puppet/indirector/msgpack.rb
  lib/puppet/reports/store.rb
  lib/puppet/util/yaml.rb
  spec/unit/file_system_spec.rb
  spec/unit/transaction/persistence_spec.rb
  spec/unit/util/storage_spec.rb
Labels: Night's Watch

#7946 (maint) Backport ignore X509 purpose during cert verification
  lib/puppet/ssl/certificate_authority.rb
  spec/unit/ssl/certificate_authority_spec.rb
Labels: Coremunity

#7947 (maint) Speed up rspec tests
  lib/puppet/test/test_helper.rb
  spec/integration/indirector/facts/facter_spec.rb
  spec/unit/application/apply_spec.rb
  spec/unit/configurer/fact_handler_spec.rb
  spec/unit/configurer_spec.rb
  spec/unit/indirector/catalog/compiler_spec.rb
  spec/unit/puppet_pal_2pec.rb
Labels: Coremunity

#7936 (PUP-10169) Generalize forcelocal parameter for user/group
  lib/puppet/provider/aix_object.rb
  lib/puppet/provider/group/aix.rb
  lib/puppet/provider/group/groupadd.rb
  lib/puppet/provider/user/aix.rb
  lib/puppet/provider/user/useradd.rb
  lib/puppet/type/group.rb
  lib/puppet/type/user.rb
  spec/unit/provider/aix_object_spec.rb
  spec/unit/provider/group/groupadd_spec.rb
  spec/unit/provider/user/useradd_spec.rb
  spec/unit/type/user_spec.rb
Labels: Night's Watch

#7949 (maint) Merge 5.5.x to 6.4.x
  lib/puppet/test/test_helper.rb
  spec/integration/indirector/facts/facter_spec.rb
  spec/unit/application/apply_spec.rb
  spec/unit/configurer/fact_handler_spec.rb
  spec/unit/configurer_spec.rb
  spec/unit/indirector/catalog/compiler_spec.rb
  spec/unit/puppet_pal_2pec.rb
  spec/unit/puppet_pal_catalog_spec.rb
Labels: Coremunity

#7945 (PUP-10246) Use dsimport to set OS X user passwords on macOS 10.15 and higher
  acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb
  lib/puppet/provider/user/directoryservice.rb
  spec/unit/provider/user/directoryservice_spec.rb
Labels: Night's Watch

#7955 (PUP-10226) URL encode paths in http client
  lib/puppet/http/service.rb
  spec/unit/http/service/report_spec.rb
  spec/unit/http/service_spec.rb
Labels: Coremunity

#7954 (maint) Adjust OS X versions on acceptance tests
  acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_home.rb
  acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_uid.rb
  lib/puppet/provider/user/directoryservice.rb
Labels: Night's Watch
