Repository puppetlabs/puppet, pull requests merged in 2020-07, with the labels that each got.

#7943 (PUP-10254) Add wide terminator when converting to pointer to wide string
  lib/puppet/test/test_helper.rb
  lib/puppet/util.rb
  lib/puppet/util/windows/api_types.rb
  lib/puppet/util/windows/eventlog.rb
  lib/puppet/util/windows/principal.rb
  lib/puppet/util/windows/registry.rb
  spec/integration/defaults_spec.rb
  spec/integration/test/test_helper_spec.rb
  spec/unit/test/test_helper_spec.rb
  spec/unit/util/windows/api_types_spec.rb
Labels: Coremunity

#8172 (PUP-1289) Manage service logon credentials on Windows
  acceptance/lib/puppet/acceptance/service_utils.rb
  acceptance/tests/resource/service/windows.rb
  lib/puppet/provider/service/windows.rb
  lib/puppet/type/service.rb
  lib/puppet/util/windows/service.rb
  lib/puppet/util/windows/user.rb
  spec/integration/util/windows/user_spec.rb
  spec/unit/provider/service/windows_spec.rb
  spec/unit/type/service_spec.rb
  spec/unit/util/windows/service_spec.rb
Labels: Night's Watch

#7802 (PUP-6631): attempted to support apt-mark
  lib/puppet/provider/package/apt.rb
  spec/unit/provider/package/apt_spec.rb
  spec/unit/provider/package/aptitude_spec.rb
Labels: Community, Night's Watch
