Repository puppetlabs/puppet, pull requests merged in 2020-02, with the labels that each got.

#7564 (PUP-9750) optionally add pe_serverversion to server_facts
  lib/puppet/indirector/catalog/compiler.rb
  spec/unit/indirector/catalog/compiler_spec.rb
Labels: puppet-org

#7964 (maint) Allow File.read calls
  spec/unit/indirector/catalog/compiler_spec.rb
Labels: Coremunity

#7815 (PUP-1537) add mark property for package
  acceptance/tests/provider/package/dpkg_hold_true_package_is_latest.rb
  acceptance/tests/provider/package/dpkg_hold_true_should_preserve_version.rb
  lib/puppet/provider/package/apt.rb
  lib/puppet/provider/package/dpkg.rb
  lib/puppet/provider/package/fink.rb
  lib/puppet/provider/package/pkg.rb
  lib/puppet/type/package.rb
  spec/unit/provider/package/apt_spec.rb
  spec/unit/provider/package/aptitude_spec.rb
  spec/unit/provider/package/dpkg_spec.rb
  spec/unit/provider/package/pkg_spec.rb
Labels: Night's Watch

#7963 (PUP-10267) Support routing to the file server given a URL
  lib/puppet/http/service/file_server.rb
  lib/puppet/http/session.rb
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_fetch_if_not_on_the_local_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_not_update_if_content_on_disk_is_up-to-date.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_update_if_content_differs_on_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_mtime_is_older_on_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_no_header_specified.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_not_on_the_local_disk.yml
  spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_not_update_if_mtime_is_newer_on_disk.yml
  spec/unit/http/service/file_server_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#7953 (PUP-9465) Implement `manages_members` in the groupadd provider
  acceptance/tests/resource/group/should_manage_members.rb
  lib/puppet/provider/group/groupadd.rb
  spec/unit/provider/group/groupadd_spec.rb
Labels: Night's Watch

#7972 (PUP-10287) mailalias: comma inside commands fix
  lib/puppet/provider/mailalias/aliases.rb
  spec/fixtures/integration/provider/mailalias/aliases/test1
Labels: Night's Watch

#7968 (PUP-10227) Close the HTTP connection
  lib/puppet/network/http/connection.rb
  lib/puppet/network/http/pool.rb
  spec/unit/network/http/connection_spec.rb
  spec/unit/network/http/pool_spec.rb
Labels: Coremunity

#7971 (maint) update Facter dependency
  .gemspec
  ext/project_data.yaml
Labels: Night's Watch

#7950 (PUP-10255) Follow symlinks in environment path
  .gitignore
  lib/puppet/environments.rb
  lib/puppet/file_system/memory_file.rb
  lib/puppet/file_system/memory_impl.rb
  lib/puppet/indirector/catalog/compiler.rb
  lib/puppet/settings.rb
  spec/unit/environments_spec.rb
Labels: Server

#7959 (PUP-10142) Allow Puppet settings redefinition
  lib/puppet.rb
  spec/unit/puppet_spec.rb
Labels: Server

#7967 (PUP-10142) Add flag for global context initialization during settings configuration
  lib/puppet.rb
Labels: Server

#7975 (PUP-10142) refactor settings initialization
  lib/puppet.rb
  lib/puppet/defaults.rb
Labels: Server

#7958 (PUP-10218) Puppet incorrectly detecting stale pidfile
  lib/puppet/util/pidlock.rb
  spec/unit/util/pidlock_spec.rb
Labels: Night's Watch

#7957 (PUP-10263) facter-ng available on all platforms
  lib/puppet/defaults.rb
  spec/unit/defaults_spec.rb
Labels: Night's Watch

#7984 (maint) Close the HTTP connection prior to sleeping
  lib/puppet/http/client.rb
  spec/unit/http/client_spec.rb
Labels: Coremunity

#7976 (PUP-10286) Delete the pool entry when the last connection is borrowed
  lib/puppet/network/http/pool.rb
  spec/unit/network/http/pool_spec.rb
Labels: Coremunity

#7969 (PUP-10147) Keep track of per-site versions in the session
  lib/puppet.rb
  lib/puppet/configurer/plugin_handler.rb
  lib/puppet/http.rb
  lib/puppet/http/client.rb
  lib/puppet/http/resolver/server_list.rb
  lib/puppet/http/resolver/settings.rb
  lib/puppet/http/resolver/srv.rb
  lib/puppet/http/response.rb
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/file_server.rb
  lib/puppet/http/service/report.rb
  lib/puppet/http/session.rb
  lib/puppet/runtime.rb
  lib/puppet/test/test_helper.rb
  spec/integration/faces/plugin_spec.rb
  spec/unit/http/response_spec.rb
  spec/unit/http/service/ca_spec.rb
  spec/unit/http/service_spec.rb
Labels: Coremunity

#7985 (PUP-10294) Order dependent test failure with recent changes
  spec/unit/util/pidlock_spec.rb
Labels: Night's Watch

#7988 (PUP-10147) Don't resolve the compiler service for the locales mount
  lib/puppet/configurer/plugin_handler.rb
  lib/puppet/http/service/report.rb
  lib/puppet/http/session.rb
  spec/unit/configurer/plugin_handler_spec.rb
  spec/unit/face/plugin_spec.rb
  spec/unit/http/session_spec.rb
Labels: Coremunity

#7991 (docs) fixing link
  lib/puppet/defaults.rb
Labels: puppet-org

#7977 (PUP-8338) Stream file content when using puppet apply
  lib/puppet/type/file/source.rb
  spec/unit/type/file/source_spec.rb
Labels: Coremunity

#7992 (docs)(DOCUMENT-966) Warning for file backup docs
  lib/puppet/application/filebucket.rb
  lib/puppet/type/file.rb
Labels: puppet-org

#8001 (maint) Remove some constant redefinition warnings
  spec/unit/indirector/resource/ral_spec.rb
  spec/unit/settings/autosign_setting_spec.rb
  spec/unit/transaction_spec.rb
  spec/unit/type/file/ensure_spec.rb
  spec/unit/util/at_fork_spec.rb
Labels: Coremunity

#7986 (PUP-9566) Include user-specified headers in http requests
  lib/puppet/defaults.rb
  lib/puppet/http/service.rb
  lib/puppet/settings.rb
  lib/puppet/settings/http_extra_headers_setting.rb
  spec/unit/http/service/ca_spec.rb
  spec/unit/http/service/compiler_spec.rb
  spec/unit/http/service/file_server_spec.rb
  spec/unit/http/service/report_spec.rb
  spec/unit/http/service_spec.rb
  spec/unit/settings/http_extra_headers_spec.rb
Labels: Coremunity

#7993 (PUP-2641) Try harder to print type's description
  lib/puppet/application/describe.rb
  spec/unit/application/describe_spec.rb
Labels: Coremunity

#8000 (PUP-10288) Close http pool before sleeping
  lib/puppet/application/device.rb
  lib/puppet/configurer.rb
  lib/puppet/face/plugin.rb
  lib/puppet/http/client.rb
  lib/puppet/ssl/state_machine.rb
  spec/unit/ssl/state_machine_spec.rb
Labels: Coremunity

#8006 (PUP-10260) Add rest terminus tests
  spec/unit/indirector/catalog/rest_spec.rb
  spec/unit/indirector/facts/rest_spec.rb
  spec/unit/indirector/file_content/rest_spec.rb
  spec/unit/indirector/file_metadata/rest_spec.rb
  spec/unit/indirector/node/rest_spec.rb
  spec/unit/indirector/report/rest_spec.rb
  spec/unit/indirector/status/rest_spec.rb
  spec/unit/type/file/source_spec.rb
Labels: Coremunity

#8007 (PUP-10260) Add http service methods
  lib/puppet/http/service.rb
  lib/puppet/http/service/ca.rb
  lib/puppet/http/service/compiler.rb
  lib/puppet/http/service/file_server.rb
  lib/puppet/http/service/report.rb
  spec/unit/http/service/compiler_spec.rb
  spec/unit/http/service/file_server_spec.rb
Labels: Coremunity
