Repository puppetlabs/puppet, pull requests merged in 2023-11, with the labels that each got.

#9138 (PUP-11985) correctly enable module:stream without default profile with dnfmodule
  lib/puppet/provider/package/dnfmodule.rb
  spec/unit/provider/package/dnfmodule_spec.rb
Labels: bug

#9073 (maint) Simplifies SSLContext intialization
  lib/puppet/ssl/ssl_context.rb
Labels: maintenance

#9152 (PUP-11937) Skip autorequire if exec's param is deferred and lazily evaluated
  lib/puppet/type/exec.rb
  spec/unit/type/exec_spec.rb
Labels: bug

#9150 (PUP-11685) Update total fact count
  lib/puppet/configurer.rb
Labels: bug

#9153 Add support for labeling pull requests
  .github/workflows/jira.yml
Labels: skip-changelog

#8919 (PUP-11593) Gentoo: Fix systemd service provider
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: bug

#9161 (PUP-11593) Gentoo: Set systemd as default provider
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: bug

#9158 Make cache and values fully thread-safe
  lib/puppet/settings.rb
Labels: triaged, bug
