Repository puppetlabs/puppet, pull requests merged in 2024-06, with the labels that each got.

#9345 Update splaylimit during daemon run
  lib/puppet/daemon.rb
  lib/puppet/scheduler/splay_job.rb
  spec/unit/daemon_spec.rb
Labels: bug

#9379 Update Beaker to 6 and beaker-puppet to 4
  acceptance/Gemfile
Labels: maintenance

#9393 Check for nil before closing Uniquefile
  lib/puppet/util/execution.rb
  spec/unit/util/execution_spec.rb
Labels: bug

#9392 Add server facts when looking up values
  lib/puppet/application/lookup.rb
  lib/puppet/indirector/catalog/compiler.rb
  lib/puppet/node/server_facts.rb
  spec/fixtures/unit/application/environments/production/data/common.yaml
  spec/unit/application/lookup_spec.rb
Labels: bug

#9351 Respect Regexp.compile method signature
  lib/puppet/functions/regsubst.rb
Labels: bug

#9397 (PUP-1881) Correct Windows runinterval behavior
  ext/windows/service/daemon.rb
Labels: bug

#9401 (PUP-1881) Correct Windows runinterval behavior
  ext/windows/service/daemon.rb
Labels: bug

#9400 Use bundler-cache to bundle install and cache gems
  .github/workflows/rspec_tests.yaml
Labels: maintenance

#9402 [Backport 7.x] Use bundler-cache to bundle install and cache gems
  .github/workflows/rspec_tests.yaml
Labels: maintenance

#9398 (PUP-12029) Prepare for Ruby 3.3
  Gemfile
  puppet.gemspec
  spec/unit/interface_spec.rb
Labels: enhancement

#9294 (PUP-11655) Use run_mode for better platform independence
  lib/puppet/defaults.rb
  lib/puppet/provider/package/gem.rb
  lib/puppet/provider/package/puppet_gem.rb
  lib/puppet/util/run_mode.rb
  spec/unit/provider/package/puppet_gem_spec.rb
  spec/unit/provider/package/puppetserver_gem_spec.rb
  spec/unit/util/run_mode_spec.rb
Labels: enhancement
