Repository puppetlabs/puppet, pull requests merged in 2024-02, with the labels that each got.

#9239 (PUP-12020) Skip tests on debian-12-amd64
  acceptance/tests/resource/exec/should_run_command_in_cwd.rb
  acceptance/tests/utf8/utf8-in-function-args.rb
Labels: triaged

#9249 Drop specs when building gem
  ext/project_data.yaml
Labels: maintenance

#9250 [Backport 7.x] Drop specs when building gem
  ext/project_data.yaml
Labels: maintenance

#9246 Update Beaker result proxies on host object
  acceptance/lib/puppet/acceptance/environment_utils.rb
  acceptance/lib/puppet/acceptance/module_utils.rb
  acceptance/lib/puppet/acceptance/service_utils.rb
  acceptance/tests/agent/agent_disable_lockfile.rb
  acceptance/tests/environment/can_enumerate_environments.rb
  acceptance/tests/environment/directory_environment_production_created_master.rb
  acceptance/tests/pluginsync/7316_faces_with_app_stubs_should_be_available_via_pluginsync.rb
  acceptance/tests/resource/service/should_query_all.rb
  acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb
Labels: maintenance

#9251 Backport #9246 to 7.x
  acceptance/lib/puppet/acceptance/environment_utils.rb
  acceptance/lib/puppet/acceptance/module_utils.rb
  acceptance/lib/puppet/acceptance/service_utils.rb
  acceptance/tests/agent/agent_disable_lockfile.rb
  acceptance/tests/environment/can_enumerate_environments.rb
  acceptance/tests/environment/directory_environment_production_created_master.rb
  acceptance/tests/pluginsync/7316_faces_with_app_stubs_should_be_available_via_pluginsync.rb
  acceptance/tests/resource/service/should_query_all.rb
  acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb
Labels: maintenance

#9253 Return boolean instead of Beaker::Result
  acceptance/tests/resource/service/init_on_systemd.rb
Labels: maintenance

#9266 (packaging) Bump to version '8.6.0' [no-promote]
  .gemspec
  lib/puppet/version.rb
Labels: maintenance

#9265 Remove Accept-Encoding header on redirect
  lib/puppet/http/redirector.rb
  spec/unit/http/client_spec.rb
Labels: bug

#9269 Accept UnaryMinusExpression as class parameter type
  lib/puppet/pops/evaluator/literal_evaluator.rb
  lib/puppet/pops/validation/validator_factory_4_0.rb
  spec/unit/pops/evaluator/literal_evaluator_spec.rb
  spec/unit/pops/validator/validator_spec.rb
Labels: bug

#9271 Stop installing i18n module from the forge during beaker tests
  acceptance/tests/environment/should_find_existing_production_environment.rb
  acceptance/tests/i18n/modules/puppet_agent.rb
Labels: maintenance
