Repository puppetlabs/puppet, pull requests merged in 2024-09, with the labels that each got.

#9468 Hardcode hostname and domain
  lib/puppet/reference/configuration.rb
  lib/puppet/settings.rb
  rakelib/generate_references.rake
Labels: maintenance

#9473 (PUP-12076) Fix windows password compliance issue
  acceptance/tests/resource/service/windows.rb
Labels: backport 7.x

#9477 (PUP-11949) Set systemd as default for Raspbian 12
  lib/puppet/provider/service/systemd.rb
  spec/unit/provider/service/systemd_spec.rb
Labels: enhancement

#9472 (PUP-12055) Build references on commit to main
  .github/workflows/references.yaml
Labels: maintenance

#9303 (#9302) Add Ruby 3.3 to CI matrix
  .github/workflows/rspec_tests.yaml
  Gemfile
  spec/unit/x509/cert_provider_spec.rb
Labels: enhancement

#9481 (maint) Update pip provider regex
  lib/puppet/provider/package/pip.rb
  spec/unit/provider/package/pip_spec.rb
Labels: bug

#9482 Use token to check out reference action
  .github/workflows/references.yaml
Labels: maintenance

#9471 (PUP-12077) Respect rich_data setting in base context
  lib/puppet.rb
  lib/puppet/application/resource.rb
  lib/puppet/resource.rb
  spec/integration/application/apply_spec.rb
  spec/unit/application/resource_spec.rb
  spec/unit/resource/catalog_spec.rb
  spec/unit/resource_spec.rb
Labels: bug

#9476 (maint) Remove needless check in setting default
  ext/windows/service/daemon.rb
Labels: bug

#9491 (PA-7090) Correct system time on AIX
  acceptance/tests/ssl/certificate_extensions.rb
Labels: maintenance
