Repository puppetlabs/puppet, pull requests merged in 2024-05, with the labels that each got.

#9326 Update validate_data_hash to return modified hash
  lib/puppet/pops/lookup/module_data_provider.rb
  spec/unit/functions/lookup_fixture_spec.rb
Labels: bug

#9337 [Backport 7.x] (PUP-12031) Consolidate gem depenendencies & metadata into puppet.gemspec
  .gemspec
  Gemfile
  Rakefile
  ext/project_data.yaml
  puppet.gemspec
  spec/unit/provider/user/directoryservice_spec.rb
Labels: enhancement

#9342 [Backport 7.x] (FACT-3434) Accept ffi >= 1.16.3, < 1.17.0
  Gemfile
  puppet.gemspec
Labels: enhancement

#9347 (maint) - Update Hiera Example
  examples/hiera/README.md
  examples/hiera/data/common.yaml
  examples/hiera/data/dc1.yaml
  examples/hiera/etc/hiera.yaml
  examples/hiera/etc/hieradb/common.yaml
  examples/hiera/etc/hieradb/dc1.yaml
  examples/hiera/etc/hieradb/development.yaml
  examples/hiera/etc/puppet.conf
  examples/hiera/hiera.yaml
  examples/hiera/modules/data/manifests/common.pp
  examples/hiera/modules/ntp/data/common.yaml
  examples/hiera/modules/ntp/hiera.yaml
  examples/hiera/modules/ntp/manifests/config.pp
  examples/hiera/modules/ntp/manifests/data.pp
  examples/hiera/modules/ntp/templates/ntp.conf.epp
  examples/hiera/modules/ntp/templates/ntp.conf.erb
  examples/hiera/modules/users/manifests/common.pp
  examples/hiera/modules/users/manifests/dc1.pp
  examples/hiera/modules/users/manifests/development.pp
  examples/hiera/site.pp
Labels: maintenance

#9331 Simplify Rakefile
  Rakefile
  rakelib/benchmark.rake
  rakelib/cfpropertylist.rake
  rakelib/ci.rake
  rakelib/generate_ast_model.rake
  rakelib/generate_cert_fixtures.rake
  rakelib/manpages.rake
  rakelib/memwalk.rake
  rakelib/parallel.rake
  rakelib/parser.rake
  rakelib/yard.rake
Labels: maintenance

#9360 Bump to JRuby 9.3.14.0, reenable test
  .github/workflows/rspec_tests.yaml
  lib/puppet/node/environment.rb
  spec/unit/file_system/path_pattern_spec.rb
Labels: maintenance

#9364 (PA-6427) Add rake tasks for building nightly gem
  Rakefile
  puppet.gemspec
Labels: maintenance

#9368 Mark some failing 8.3 Windows tests as pending
  .github/workflows/rspec_tests.yaml
  spec/integration/directory_environments_spec.rb
  spec/integration/node/environment_spec.rb
  spec/unit/file_system_spec.rb
  spec/unit/util/autoload_spec.rb
Labels: maintenance

#9367 Drop remnants of `rake package:apple` support
  ext/project_data.yaml
  rakelib/cfpropertylist.rake
Labels: maintenance

#9374 [Backport 7.x] Drop remnants of rake package:apple support
  ext/project_data.yaml
  tasks/cfpropertylist.rake
Labels: maintenance

#9372 [Backport 7.x] Add rake tasks for building nightly gem
  Rakefile
  puppet.gemspec
Labels: maintenance

#8976 (maint) Add xbps used by voidlinux as a package provider
  lib/puppet/provider/package/xbps.rb
  spec/unit/provider/package/xbps_spec.rb
Labels: enhancement
