Repository puppetlabs/puppet, pull requests merged in 2024-10, with the labels that each got.

#9495 Revert "(PA-7090) Correct system time on AIX"
  acceptance/tests/ssl/certificate_extensions.rb
Labels: maintenance

#9497 tidy: Clarify meaning of numeric `recurse` values
  lib/puppet/type/tidy.rb
Labels: bug

#8799 (PUP-11326) Make regsubst() sensitive-aware
  lib/puppet/functions/regsubst.rb
  spec/unit/functions/regsubst_spec.rb
Labels: enhancement

#9511 Fix typo in comparison operator
  acceptance/tests/resource/user/should_create_modify_with_password.rb
Labels: maintenance
